server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: inditex-technical-test
  datasource:
    url: ${DATABASE_CONNECTION}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: ${DATABASE_DIALECT}
    database: {$DATABASE_TYPE}
    openInView: false
    show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
  liquibase:
    change-log: classpath:db/changelog-root.xml
  h2:
    console:
      enabled: true
      path: /h2-console